apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/instance: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/instance: default
  ports:
    - name: http
      port: 80
      targetPort: 8080
