apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Namespace
metadata:
  name: sales
---
apiVersion: v1
kind: Namespace
metadata:
  name: inventory
---
apiVersion: v1
kind: Namespace
metadata:
  name: users
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
