apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-only-needed
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
