# Ingress NGINX
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-nginx
spec:
 rules:
 - host: novacommerce.local
 http:
 paths:
 - path: /
 pathType: Prefix
 backend:
 service:
 name: webstore
 port:
 number:80
