replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/festive-shield-443319-q5/nova-repo/inventory
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
