name: Build, Test, and Push to GCP

on:
  push:
    branches: [ main-developers ]
  pull_request:
    branches: [ main-developers ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        service: [sales, inventory, identity, gateway, catalog, payments, users-auth, outbox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          # Usa la versión
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker auth'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Service
        run: |
          SERVICE_NAME=${{ matrix.service }}
          DOCKERFILE_PATH="services/$SERVICE_NAME/Dockerfile"
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/nova-repo/$SERVICE_NAME-service:${{ github.sha }} -f $DOCKERFILE_PATH .
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/nova-repo/$SERVICE_NAME-service:${{ github.sha }}
